### ISSUE TITLE
no-empty в пустом catch

### ISSUE THREAD

**Issue by meritt** [htmlacademy/eslint-config-htmlacademy#12]
Получаю `no-empty` ошибку если внутри `catch` ничего не будет. Пример для теста:

```js
try {
  client.emit('message', JSON.stringify(data));
} catch (ignore) {
  // empty catch
}
```

**Comment by zeckson** [comment]
Правило просит указать причину пустого блока. 
Пустой блок кода без пояснений — это действительно странная конструкция.
Правило требует оставить комментарий, почему ошибка не обрабатывается:
```
Empty block statements, while not technically errors, usually occur due to refactoring that wasn’t completed. They can cause confusion when reading code.
```
всегда можно отключить в своём конфиге при помощи `'no-empty': 'off'`
