### ISSUE TITLE
no-process-exit

### ISSUE THREAD

**Issue by o0** [htmlacademy/eslint-config-htmlacademy#2]
Предлагаю разрешить, но запрещать на уровне ревью кода делать `process.exit` не в модуле верхнего уровня

http://eslint.org/docs/rules/no-process-exit

**Comment by princed** [comment]
Так не работает, Игорь =)

И вообще, зачем? Есть же throw.

**Comment by o0** [comment]
Ну `throw` выглядит очень некрасиво, он просто выбрасывает и выводит чо попало. `process.exit()` более контролируем, для него можно написать адекватное сообщение, ну и вообще это тру вэй.

А почему не работает? Потому что надо проверять каждый случай отдельно и нет автоматизации?

**Comment by zeckson** [comment]
@o0 define `красиво`? 
> process.exit() более контролируем, для него можно написать адекватное сообщение, ну и вообще это тру вэй.
Игорь, в этом как раз и дело, что у `exit` — нет сообщения, он не требует от тебя сообщения. Поэтому есть куча программ на `windows` которые выходят и говорят `Ошибка 228. Пока!`. `throw` гораздо адекватнее в этом плане. Есть исключения — программы утилиты, в которых ты пишешь специальный выход и пишешь `exit`. Для этого случая я думаю можно воспользоваться игнором в виде коммента.

**Comment by princed** [comment]
Там вообще в описании правила написано, почему оно нужно вообще :)

**Comment by zeckson** [comment]
@princed на самом деле, я скопировал эту опцию из оригинального конфига Игоря, но, внезапно, сам Игорь взбрыкнул =)

**Comment by zeckson** [comment]
Используйте `throw`
