### ISSUE TITLE
Пробелы в деструктуризации и в однострочных объектах между фигурными скобками

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/eslint-config-htmlacademy#3]
Пример:
```
let obj = { a: 100, b: 200 };
let { a, b } = obj;
```

**Comment by princed** [comment]
Отличная возможность сделать, как тебе больше нравится :)

**Comment by healqq** [comment]
Я бы по логике с параметрами функций сделал как раз без пробелов. Так более единообразно работа со скобками выглядит:
```javascript
function (a, b) {};     
let obj = {a: 100, b: 200};
let {a, b} = obj;
```

**Comment by zeckson** [comment]
@healqq идея как раз в том, что это не скобки и хотелось бы разделить поведение скобой и объектов.

**Comment by healqq** [comment]
@zeckson ну если не с параметрами у функций - то с массивами должно как-то коррелировать:
```javascript
const array = [1, 2, 3];
const object = {a: 100, b: 200};
```
P.S. вот Airbnb например [требуют](http://airbnb.io/javascript/#whitespace--in-braces) как ты предлагаешь, но не говорят почему.

**Comment by zeckson** [comment]
Мне нравится когда воздуха больше, т.е. с пробелами как у Airnbnb

**Comment by healqq** [comment]
Меня больше смущает что в массивах пробелов нет, а в объектах есть. Хотя по сути и то и другое - коллекция.

**Comment by zeckson** [comment]
Сделал без пробелов:
```
// http://eslint.org/docs/rules/array-bracket-spacing.html
// http://eslint.org/docs/rules/object-curly-spacing.html
const [a, , c] = [1, 2, 3];
const {d, e} = {a: 1, b: 2};
const obj = {a, c, d, e};
throw new Error(a, c, d, e, obj);
```
