### ISSUE TITLE
Increase `max-nested-callbacks` to 5

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/eslint-config-htmlacademy#38]
Due to callback nature of tests, like `mocha` it makes really difficult to write tests with limit of 3 nested callbacks.
I think we can increase this limit to 5.

**Comment by zeckson** [comment]
@healqq good idea! But as far as I know you can't split rules by filenames in ESlint and add more configs here is not a good idea either, since it will multiply every config by 2 =(
If you have a good solution, please share.

**Comment by healqq** [comment]
you can put a .eslintjson inside /test that with something like that:
```{

**Comment by zeckson** [comment]
Oh, yes! We can try to go with `overrides`. Thank you so much!

**Comment by kam4atka** [comment]
This rule is not used in the new configuration file.
