### ISSUE TITLE
Разрешать шаблонные строки даже если это не шаблон

### ISSUE THREAD

**Issue by zeckson** [htmlacademy/eslint-config-htmlacademy#4]
Разрешить:
```
const string = `Template string`;
```

**Comment by princed** [comment]
Только если это единственный тип строк.

Основное правило — не должно быть можно несколькими способами написать одно и то же.

**Comment by healqq** [comment]
Шаблонные строки по логике должны быть медленнее, может как раз стоит запретить использование для константных строк? Как пример - PHPшные линтеры ругаются, если используется синтаксис для шаблонных строк, а шаблона нет.
Но вообще вариант  @princed  мне тоже нравится.

**Comment by zeckson** [comment]
> Шаблонные строки по логике должны быть медленнее

Есть какие-нибудь перформанс тесты? Статьи? Почему они должны быть медленнее?

> Только если это единственный разрешенный синтаксис строк.

Я тоже думал об этом, но почему?

**Comment by princed** [comment]
> Я тоже думал об этом, но почему?

Почему единственный?
> Основное правило — не должно быть можно несколькими способами написать одно и то же.

Почему это хорошая идея?
Не надо бесконечно менять тип кавычек, если ты добавляешь или убираешь интерполяцию.

**Comment by healqq** [comment]
По поводу производительности нашел только такое: http://www.incaseofstairs.com/2015/06/es6-feature-performance/ - там какие-то вообще страшные числа у Babel стоят.
Попробовал на jsPref: https://jsperf.com/template-strings-test для нативной реализации разницы никакой.

**Comment by princed** [comment]
@zeckson Мы тут, договорились, кажется =)

**Comment by zeckson** [comment]
fixed

**Comment by zeckson** [comment]
@princed есть проблема. Шаблонные строки запрещены в `import`. Т.е. вот так нельзя:
```
import something from `./some-module`
```

**Comment by princed** [comment]
Я бы скорее сделал исключение для импорта, чем как-то по-другому.

**Comment by zeckson** [comment]
Ок

**Comment by zeckson** [comment]
Еще шаблоны не работаю в ключах объектов:
```
const obj = {
  `not working`: 1234
}
```

**Comment by princed** [comment]
На объекты он и не ругается вроде, не надо ничего менять.

```[`this is working`]: 1234```
Нет такого правила в любом случае.

**Comment by zeckson** [comment]
> На объекты он и не ругается вроде, не надо ничего менять.

Имеется ввиду что там опять же строки, т.е. не везде можно использовать шаблоны.

**Comment by princed** [comment]
¯\_(ツ)_/¯

**Comment by BekoBou** [comment]
@zeckson Если мы всё равно не можем отказаться сейчас от одинарных кавычек, то почему бы их не разрешить использовать наравне с шаблонными строками? То есть запретить только двойные кавычки.

**Comment by zeckson** [comment]
@BekoBou мы можем отказаться от одинарных кавычек при создании строк, но не можем отказаться от них когда это является частью конструкции. Как отличить строку от монолитной конструкции — очень просто, попробовать положить её в переменную, если не получиться, то это конструкция, если получится, то строка. Приведу пример:
```js
const file = './file';
import something from file; // так делать нельзя, т.к. './file' неразрывная конструкция https://developer.mozilla.org/en/docs/Web/JavaScript/Reference/Statements/import

const a = 'long name';
const myObj = {
  a: `value` // здесь "a" означает саму себя и является частью конструкции и не подставляется, поэтому вынести в переменную эту строку нельзя
}
```

Почему мы запрещаем использовать одинарные кавычки в строковых литералах:
- можно использовать кавычки внутри строки не экранируя символы:
```js
const string = `'не надо экранировать " и ' '`;
- не нужно менять тип строки, если шаблона внутри не стало:
```js
const name = `Вася`;
const templateString = `Привет, ${name}!`;
// если я уберу интерполяцию, то eslint потребует и поменять тип строки
const regularString = `Привет!`; // ошибка eslint
```
- форсит использовать интерполяцию вместо конкатенации
- не размножает кол-во способов объявить сделать одно и то же (бритва Оккама)

**Comment by BekoBou** [comment]
> можно использовать кавычки внутри строки не экранируя символы

Вместо этого мы должны экранировать другие символы:
```javascript
let a = 2;
let b = 3;
let s = `\`\${ a + b }\` = ${ a + b }`; // "`${ a + b }` = 5"
```

> не размножает кол-во способов объявить сделать одно и то же (бритва Оккама)

А завтра нам запретят инкремент! Надо разумно запрещать.

```javascript
let i = 0;
i++;
i += 1;
i = i + 1;
```

То есть я правильно понимаю, что мы используем шаблонные строки везде потому, что если мы отменим это правило, то eslint будет заставлять использовать строки в шаблонах без интерполяции?

**Comment by zeckson** [comment]
> Вместо этого мы должны экранировать другие символы:

Я имел ввиду средний случай, когда в тексте строки встречаются кавычки. Вот немного (статистики)[https://news.ycombinator.com/item?id=2973776] из C-программ. Если найдешь более лучшую статистику, буду признателен.
```
    _  22890057
    ,  10895692
    )  10749798
    (  10745839
    *  9211904
    ;  8187969
    -  6628768
    =  5878296
    >  4428291
    /  3468260
    .  3011078
    {  2212412
    }  2211783
    "  2120264
    &  1647188
    :  1032587
    +  962554
    #  909859
    [  889538
    ]  888722
    <  839910
    |  643903
    %  583092
    !  561462
    \  540456
    '  454201
    @  131199
    ?  112488
    ~  84629
    ^  19064
    $  17922
    `  7272
    [space] 74199965
```

> А завтра нам запретят инкремент! Надо разумно запрещать.

Да, надо. Разумно и запрещаем.

> То есть я правильно понимаю, что мы используем шаблонные строки везде потому, что если мы отменим это правило, то eslint будет заставлять использовать строки в шаблонах без интерполяции?

Если проигнорировать все остальные аргументы, то да.

Буду рад услышать встречные предложения и аргументированную точку зрения по данному вопросу. Желательно с примерами.
Спасибо!
