### ISSUE TITLE
trailing commas

### ISSUE THREAD

**Issue by utrumo** [htmlacademy/eslint-config-htmlacademy#40]
https://github.com/htmlacademy/eslint-config-htmlacademy/blob/99aad6885d90120e07f20449c6b840564c5fc3be/es5.js#L117

["При создании непустых объектов и массивов не используются «висячие» запятые"
](http://codeguide.academy/javascript.html)
"only-multiline" allows (but does not require) trailing commas when the last element or property is in a different line than the closing ] or } and disallows trailing commas when the last element or property is on the same line as the closing ] or }
https://eslint.org/docs/rules/comma-dangle

**Comment by kam4atka** [comment]
We have fixed this error. Thank you for your issue.
